### ISSUE TITLE
MVP checklist

### ISSUE THREAD

**Issue by dfhoughton** [dfhoughton/jobrog#1]
- [x] append event
- [x] append note
- [x] ensure base directory
- [x] done subcommand
- [x] resume subcommand
- [x] edit subcommand
- [x] truncate subcommand
- [x] vacation subcommand
- [x] fix tests which are reading the wrong log
- [x] review all help text
- [x] assign useful order to subcommands

**Comment by dfhoughton** [comment]
Another checklist: **Things to Validate**

- [x] all timestamps in order
- [x] no DONE without a preceding event
- [x] no future timestamps

**Comment by dfhoughton** [comment]
### Tests to write
- [x] vacation overlap tests
- [x] christmas mislabeling regression test
- [ ] validation tests

**Comment by dfhoughton** [comment]
- [x] --rx bug: `cargo run -- s --rx gresb ever`
- [x] when bug
- [x] colorize "ongoing"

**Comment by dfhoughton** [comment]
# inappropriate merge bug
- [x] fixme
```
➜  starbucks-sourcing-apps (master|✔) job s -d fri -t sb
Friday, 10 January
  9:41 am - 10:50    1.16  30, mr, sb  Create roaster view which lets you add people to roaster                        
    10:50 - 3:46 pm  4.92  10, mr, sb  get multi-tenant S3 attachments to work; get multi-tenant S3 attachments to work
     3:46 - 3:50     0.08  29, mr, sb  Make it so the Spectrum API is only called for starbucks stuff                  
     3:50 - 3:50     0.00  mtg, sb     GR/SCS Monthly Check-In                                                         
     3:50 - 4:01     0.18  29, mr, sb  Make it so the Spectrum API is only called for starbucks stuff                  
     4:01 - 4:30     0.48  mtg, sb     GR/SCS Monthly Check-In                                                         
     4:30 - 5:01     0.52  29, mr, sb  Make it so the Spectrum API is only called for starbucks stuff                  

TOTAL HOURS 7.35
10          4.92
29          0.78
30          1.16
mr          6.86
mtg         0.48
sb          7.35
➜  starbucks-sourcing-apps (master|✔) job s -d fri -t sb -t mtg
Friday, 10 January
  3:50 pm - 4:30  0.67  mtg, sb  GR/SCS Monthly Check-In; GR/SCS Monthly Check-In

TOTAL HOURS 0.67
mtg         0.67
sb          0.67
```
Note the change in `mtg` time.

**Comment by dfhoughton** [comment]
- [x] FIXME
```
➜  starbucks-vrs-shipping (master|✔) job s ever
thread 'main' panicked at 'assertion failed: self.end.is_none() || self.end.unwrap() > time', src/log.rs:1478:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```
